// Thematic data is served as a static file at /public/thematic_graph.json
// (generated by Databricks notebook 06_gold_thematic_embeddings.ipynb)
// workspace.gold schema is not accessible from the SQL Warehouse without an explicit GRANT.
// To enable live queries instead, run in Databricks:
//   GRANT USE SCHEMA ON SCHEMA workspace.gold TO `<warehouse service principal>`;
//   GRANT SELECT ON TABLE workspace.gold.film_embeddings TO `<warehouse service principal>`;
//   GRANT SELECT ON TABLE workspace.gold.thematic_edges TO `<warehouse service principal>`;

export async function GET() {
  return Response.json(
    { error: "Serve thematic data via /thematic_graph.json static file in public/" },
    { status: 404 }
  )
}
